# Generated by Django 4.0.4 on 2022-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productinventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
