# Generated by Django 4.0.4 on 2022-08-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_description'),
        ('orders', '0004_order_total_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.store'),
            preserve_default=False,
        ),
    ]
