# Generated by Django 4.0.4 on 2022-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bank Manager'), (2, 'Ecommerce Admin'), (3, 'Seller'), (4, 'Customer')], null=True),
        ),
    ]
