# Generated by Django 4.0.4 on 2022-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_address_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
