# Generated by Django 4.0.4 on 2022-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='profile_pictures/'),
        ),
    ]
