# Generated by Django 4.0.4 on 2022-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
