# Generated by Django 4.0.4 on 2022-08-03 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_no', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('credential', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], max_length=1)),
                ('type', models.CharField(choices=[('I', 'Cash In'), ('S', 'Send To')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_from', to='bank.bankaccount')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_to', to='bank.bankaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
