# Generated by Django 4.0.4 on 2022-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bankoption_key_alter_bankoption_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
