# Generated by Django 4.0.4 on 2022-08-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credential',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
